modLoader="javafml"
loaderVersion="*"
license="MIT License"
logoFile="windswept_integration.png"
logoBlur=false

[[mods]]
modId="windswept_integration"
displayName="Windswept Integration"
version="2.0.0"
authors="SkellaTex"
description='''
Additional mod compatibility for Windswept.
'''

[[mixins]]
config="windswept_integration.mixins.json"

[[dependencies.windswept_integration]]
modId="minecraft"
versionRange="1.21.1"
ordering="NONE"
side="BOTH"

[[dependencies.windswept_integration]]
modId="blueprint"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.windswept_integration]]
modId="windswept"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.windswept_integration]]
modId="environmental"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.windswept_integration]]
modId="snowyspirit"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

